#
# /fac <команда> | forallcommands.use - Позволит выполнить команду от имени консоли для всех игроков.
# Например, в плагине EssentialsX, есть * и ** которые позволяют выполнить что-либо для всех онлайн игроков,
# но, есть плагины, где такого нет, для этого и существует мой плагин!
#
# Чтобы перезагрузить конфиг введите /fac без аргументов
#

messages:
  no-permission: "§cУ вас нет прав!"
  done: "§b▶ §fКоманда §b/%command% §fвыполнена для всех игроков!"
  reloaded: "§aКонфигурация успешно перезагружена!"